//
//  Copyright 2013 Acer Cloud Technology Inc.
//  All Rights Reserved.
//
//  THIS SOFTWARE CONTAINS CONFIDENTIAL INFORMATION AND
//  TRADE SECRETS OF ACER CLOUD TECHNOLOGY INC.
//  USE, DISCLOSURE OR REPRODUCTION IS PROHIBITED WITHOUT
//  THE PRIOR EXPRESS WRITTEN PERMISSION OF ACER CLOUD
//  TECHNOLOGY INC.
//

#ifndef SYNC_CONFIG_UTIL_HPP_10_03_2013
#define SYNC_CONFIG_UTIL_HPP_10_03_2013

#include "SyncConfig.hpp"
#include "SyncConfigDb.hpp"

SyncDbFamily getSyncDbFamily(SyncType syncType);

#endif // SYNC_CONFIG_UTIL_HPP_10_03_2013
