cpp_binary(
    name = 'nearbyDevicesTest',
    includes = [
        '/gvm_core/internal/multicast_dns_discovery/include'
    ],
    srcs = [
        'nearby_devices.c'
    ],
    deps = [
        '/gvm_core/internal/multicast_dns_discovery:libmulticast_dns_discovery',
    ]
)
