.PHONY: first_target default daily

first_target:
	@echo "TC_RESULT=FAIL ;; TC_NAME=should_not_run_default_target1"

default:
	@echo "TC_RESULT=FAIL ;; TC_NAME=should_not_run_default_target2"

daily:
	@echo "TC_RESULT=PASS ;; TC_NAME=run_override_target"
