export CCDCONF_ENABLETS = 7
export CCDCONF_CLEARFIMODE = 6

include ../regression_internal_direct/Makefile

override MY_TEST_NAME=regression_internal_direct_alt_tun

.PHONY: regression_internal_direct_alt_tun
regression_internal_direct_alt_tun: regression_internal_direct
