cpp_binary(
    name = 'stabilityTest',
    includes = [
        '/gvm_core/internal/multicast_dns_discovery/include',
        '/gvm_core/internal/multicast_dns_discovery/src',
        '/gvm_core/internal/multicast_dns_discovery/platform/include',
        '/gvm_core/internal/multicast_dns_discovery/platform/linux/include',
    ],
    srcs = [
        'stability_test.c'
    ],
    deps = [
        '/gvm_core/internal/multicast_dns_discovery:libmulticast_dns_discovery',
    ]
)
