/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_igware_vplex_test_VplexNative */

#ifndef _Included_com_igware_vplex_test_VplexNative
#define _Included_com_igware_vplex_test_VplexNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_igware_vplex_test_VplexNative
 * Method:    testVPLex
 * Signature: (I[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_igware_vplex_test_VplexNative_testVPLex
  (JNIEnv *, jclass, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
