static_cpp_lib(
    name = 'protoxml',
    srcs = [
        'ProtoXmlParseState.cpp',
        'ProtoXmlParseStateImpl.cpp'
    ],
    includes = [''],
    deps = ['../protorpc', '/gvm_core/vplex:libvplexcore'],
)
