export CCDCONF_ENABLETS = 7
export CCDCONF_CLEARFIMODE = 6

include ../sdk_release_remotefile/Makefile

override MY_TEST_NAME=sdk_release_remotefile_alt_tun

.PHONY: sdk_release_remotefile_alt_tun
sdk_release_remotefile_alt_tun: sdk_release_remotefile
