//
//  Copyright 2014 Acer Cloud Technology Inc.
//  All Rights Reserved.
//
//  THIS SOFTWARE CONTAINS CONFIDENTIAL INFORMATION AND
//  TRADE SECRETS OF ACER CLOUD TECHNOLOGY INC.
//  USE, DISCLOSURE OR REPRODUCTION IS PROHIBITED WITHOUT
//  THE PRIOR EXPRESS WRITTEN PERMISSION OF ACER CLOUD
//  TECHNOLOGY INC.
//

#ifndef AUTOTEST_PHOTO_SHARE_HPP_5_1_2014_
#define AUTOTEST_PHOTO_SHARE_HPP_5_1_2014_

int do_autotest_sdk_release_photo_share(int argc, const char* argv[]);

#endif // AUTOTEST_PHOTO_SHARE_HPP_5_1_2014_
