cpp_binary(
    name = 'cJSON2Test',
    includes = ['../include'],
    srcs = [
            'cJSON2Test.c',
           ],
    deps = [
            '/gvm_core/internal/cJSON2:libcJSON2',
           ],
)

