static_cpp_lib(
    name = 'libes_core_utils',
    includes = ['include'],
    srcs = [
            'src/util_tmdgetcontentinfo.c',
           ],
    deps = [
            '/gvm_core/vplex:libvplex',
            '/gvm_core/internal/error_codes:liberror_codes',
            '/gvm_core/internal/es_viewer:libes_viewer',
            '/gvm_core/internal/log:liblog',
           ],
)
