cpp_binary(
    name = 'test_picstream',
    includes = ['../../dxshell'],
    srcs = ['test_picstream.cpp',
    		'../../dxshell/common_utils.cpp',],
    deps = [
        '/gvm_core/daemons/ccd:libccd_client',
        '/gvm_core/internal/file_utils:libfile_utils'
    ]
)
