cpp_binary(
    name = 'publishTest',
    includes = [
        '/gvm_core/internal/multicast_dns_discovery/include'
    ],
    srcs = [
        'publish_test.c'
    ],
    deps = [
        '/gvm_core/internal/multicast_dns_discovery:libmulticast_dns_discovery',
    ]
)
