cpp_binary(
    name = 'syncConfigDbTest',
    includes = [
        '/gvm_core/internal/sync_config/src'
    ],
    srcs = [
        'syncConfigDbTest.cpp'
    ],
    deps = [
        '/gvm_core/internal/sync_config:libsync_config',
        '/gvm_core/internal/file_utils:libfile_utils',
    ]
)
