include $(ROOT)/usr/include/make/GVMdefs

CFILES = vpl_threadprio_timing.c

# define the target we want to make from those C files.
TARGETS = vpl_threadprio_timing

# Boilerplate does all the rest...
include ../microbench.vpl.prog.mk

include $(GVMRULES)
