/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_igware_android_services_McaService */

#ifndef _Included_com_igware_android_services_McaService
#define _Included_com_igware_android_services_McaService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_igware_android_services_McaService
 * Method:    mcaJniProtoRpc
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_igware_android_1services_McaService_mcaJniProtoRpc
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
