export CCDCONF_ENABLETS = 7
export CCDCONF_CLEARFIMODE = 7

include ../regression_proxy/Makefile

override MY_TEST_NAME=regression_proxy_alt_tun

.PHONY: regression_proxy_alt_tun
regression_proxy_alt_tun: regression_proxy
