#! /bin/csh -fb

cd ~root/java

echo "Killing tests."

foreach i (`cat automatic-hosts`)
    ssh $i "killall java"
end

sleep 10

foreach i (`cat automatic-hosts`)
    ssh $i "killall -9 java"
end

echo "Waiting for the ports to become available."

sleep 60

foreach i (`cat automatic-hosts`)
	echo " === Starting $i"
	ssh $i "cd java; ./run-multi-local"
end
