cpp_binary(
    name = 'p2p_test',
    includes = ['/gvm_core/internal/p2p/include',
                'include',
               ],
    srcs = [
            'p2p_test.cpp',
           ],
    deps = ['/gvm_core/vplex:libvplex',
            '/gvm_core/internal/p2p:libp2p',
           ],
)
cpp_binary(
    name = 'p2p_test_server',
    includes = ['/gvm_core/internal/p2p/include',
                'include',
               ],
    srcs = [
            'p2p_test_server.cpp',
           ],
    deps = ['/gvm_core/vplex:libvplex',
           ],
)
