cpp_binary(
    name = 'actool_app',
    includes = [],
    srcs = [
            'src/actool.cpp',
           ],
    deps = [
            '/gvm_core/vpl:libvplcore',
            '/gvm_core/internal/file_utils:libfile_utils',
           ],
)
