cpp_binary(
    name = 'loadgen_orbe',
    includes = [
                '../common',
               ],
    srcs = [
            'loadgen_orbe.cpp',
            'vsTest_personal_cloud_data.cpp',
            'manifest.cpp',
            '../common/vsTest_vscs_common.cpp',
            '../common/vsTest_infra.cpp',
            '../common/vsTest_worker.cpp',
           ],
    deps = [
            '/gvm_core/internal/vssi:libvssi',
            '/gvm_core/vplex:libvplex',
           ],
)

