static_cpp_lib(
    name = 'libcontentfile',
    includes = ['include'],
    srcs = [
            'src/contentfile.c',
           ],
    deps = [
            '/gvm_core/vpl:libvplcore',
            '/gvm_core/vplex:libvplexcore',
            '/gvm_core/internal/log:liblog',
           ],
)
