static_cpp_lib(
    name = 'libes_viewer',
    includes = ['include'],
    srcs = [
            'src/cfmviewer.c',
            'src/tikviewer.c',
            'src/tmdviewer.c',
           ],
    deps = [
            '/gvm_core/internal/es_types:libes_types'
           ],
)
