/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_igware_sync_config_test_SyncConfigNative */

#ifndef _Included_com_igware_sync_config_test_SyncConfigNative
#define _Included_com_igware_sync_config_test_SyncConfigNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_igware_sync_config_test_SyncConfigNative
 * Method:    testSyncConfig
 * Signature: (I[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_igware_sync_1config_test_SyncConfigNative_testSyncConfig
  (JNIEnv *, jclass, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
