# protobuf precompiled when CCDMonitorService project is built

protobuf(
    name = 'ccdmonsrv_defs',
    protofile = 'CCDMonSrv_Defs.proto',
    input_path = 'types',
    deps = [
           ],
    cpp_out = 'types/src',
    hpp_out = 'types/include',
)
