// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vplex_sync_agent_notifier.proto

#ifndef PROTOBUF_vplex_5fsync_5fagent_5fnotifier_2eproto__INCLUDED
#define PROTOBUF_vplex_5fsync_5fagent_5fnotifier_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace vplex {
namespace syncagent {
namespace notifier {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_vplex_5fsync_5fagent_5fnotifier_2eproto();
void protobuf_AssignDesc_vplex_5fsync_5fagent_5fnotifier_2eproto();
void protobuf_ShutdownFile_vplex_5fsync_5fagent_5fnotifier_2eproto();

class DatasetUpdate;
class DatasetContentUpdate;
class SubscriptionUpdate;
class DeviceUnlinked;
class DeviceLinked;
class DeviceUpdate;
class PSNConnectionUpdate;
class UserStorageUpdate;
class SyncAgentNotification;

// ===================================================================

class DatasetUpdate : public ::google::protobuf::Message {
 public:
  DatasetUpdate();
  virtual ~DatasetUpdate();
  
  DatasetUpdate(const DatasetUpdate& from);
  
  inline DatasetUpdate& operator=(const DatasetUpdate& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const DatasetUpdate& default_instance();
  
  void Swap(DatasetUpdate* other);
  
  // implements Message ----------------------------------------------
  
  DatasetUpdate* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DatasetUpdate& from);
  void MergeFrom(const DatasetUpdate& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required fixed64 recipient_uid = 1;
  inline bool has_recipient_uid() const;
  inline void clear_recipient_uid();
  static const int kRecipientUidFieldNumber = 1;
  inline ::google::protobuf::uint64 recipient_uid() const;
  inline void set_recipient_uid(::google::protobuf::uint64 value);
  
  // required fixed64 dataset_id = 2;
  inline bool has_dataset_id() const;
  inline void clear_dataset_id();
  static const int kDatasetIdFieldNumber = 2;
  inline ::google::protobuf::uint64 dataset_id() const;
  inline void set_dataset_id(::google::protobuf::uint64 value);
  
  // @@protoc_insertion_point(class_scope:vplex.syncagent.notifier.DatasetUpdate)
 private:
  inline void set_has_recipient_uid();
  inline void clear_has_recipient_uid();
  inline void set_has_dataset_id();
  inline void clear_has_dataset_id();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint64 recipient_uid_;
  ::google::protobuf::uint64 dataset_id_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_vplex_5fsync_5fagent_5fnotifier_2eproto();
  friend void protobuf_AssignDesc_vplex_5fsync_5fagent_5fnotifier_2eproto();
  friend void protobuf_ShutdownFile_vplex_5fsync_5fagent_5fnotifier_2eproto();
  
  void InitAsDefaultInstance();
  static DatasetUpdate* default_instance_;
};
// -------------------------------------------------------------------

class DatasetContentUpdate : public ::google::protobuf::Message {
 public:
  DatasetContentUpdate();
  virtual ~DatasetContentUpdate();
  
  DatasetContentUpdate(const DatasetContentUpdate& from);
  
  inline DatasetContentUpdate& operator=(const DatasetContentUpdate& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const DatasetContentUpdate& default_instance();
  
  void Swap(DatasetContentUpdate* other);
  
  // implements Message ----------------------------------------------
  
  DatasetContentUpdate* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DatasetContentUpdate& from);
  void MergeFrom(const DatasetContentUpdate& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required fixed64 recipient_uid = 1;
  inline bool has_recipient_uid() const;
  inline void clear_recipient_uid();
  static const int kRecipientUidFieldNumber = 1;
  inline ::google::protobuf::uint64 recipient_uid() const;
  inline void set_recipient_uid(::google::protobuf::uint64 value);
  
  // required fixed64 dataset_id = 2;
  inline bool has_dataset_id() const;
  inline void clear_dataset_id();
  static const int kDatasetIdFieldNumber = 2;
  inline ::google::protobuf::uint64 dataset_id() const;
  inline void set_dataset_id(::google::protobuf::uint64 value);
  
  // @@protoc_insertion_point(class_scope:vplex.syncagent.notifier.DatasetContentUpdate)
 private:
  inline void set_has_recipient_uid();
  inline void clear_has_recipient_uid();
  inline void set_has_dataset_id();
  inline void clear_has_dataset_id();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint64 recipient_uid_;
  ::google::protobuf::uint64 dataset_id_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_vplex_5fsync_5fagent_5fnotifier_2eproto();
  friend void protobuf_AssignDesc_vplex_5fsync_5fagent_5fnotifier_2eproto();
  friend void protobuf_ShutdownFile_vplex_5fsync_5fagent_5fnotifier_2eproto();
  
  void InitAsDefaultInstance();
  static DatasetContentUpdate* default_instance_;
};
// -------------------------------------------------------------------

class SubscriptionUpdate : public ::google::protobuf::Message {
 public:
  SubscriptionUpdate();
  virtual ~SubscriptionUpdate();
  
  SubscriptionUpdate(const SubscriptionUpdate& from);
  
  inline SubscriptionUpdate& operator=(const SubscriptionUpdate& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SubscriptionUpdate& default_instance();
  
  void Swap(SubscriptionUpdate* other);
  
  // implements Message ----------------------------------------------
  
  SubscriptionUpdate* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SubscriptionUpdate& from);
  void MergeFrom(const SubscriptionUpdate& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required fixed64 recipient_uid = 1;
  inline bool has_recipient_uid() const;
  inline void clear_recipient_uid();
  static const int kRecipientUidFieldNumber = 1;
  inline ::google::protobuf::uint64 recipient_uid() const;
  inline void set_recipient_uid(::google::protobuf::uint64 value);
  
  // required fixed64 device_id = 2;
  inline bool has_device_id() const;
  inline void clear_device_id();
  static const int kDeviceIdFieldNumber = 2;
  inline ::google::protobuf::uint64 device_id() const;
  inline void set_device_id(::google::protobuf::uint64 value);
  
  // required fixed64 dataset_id = 3;
  inline bool has_dataset_id() const;
  inline void clear_dataset_id();
  static const int kDatasetIdFieldNumber = 3;
  inline ::google::protobuf::uint64 dataset_id() const;
  inline void set_dataset_id(::google::protobuf::uint64 value);
  
  // @@protoc_insertion_point(class_scope:vplex.syncagent.notifier.SubscriptionUpdate)
 private:
  inline void set_has_recipient_uid();
  inline void clear_has_recipient_uid();
  inline void set_has_device_id();
  inline void clear_has_device_id();
  inline void set_has_dataset_id();
  inline void clear_has_dataset_id();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint64 recipient_uid_;
  ::google::protobuf::uint64 device_id_;
  ::google::protobuf::uint64 dataset_id_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_vplex_5fsync_5fagent_5fnotifier_2eproto();
  friend void protobuf_AssignDesc_vplex_5fsync_5fagent_5fnotifier_2eproto();
  friend void protobuf_ShutdownFile_vplex_5fsync_5fagent_5fnotifier_2eproto();
  
  void InitAsDefaultInstance();
  static SubscriptionUpdate* default_instance_;
};
// -------------------------------------------------------------------

class DeviceUnlinked : public ::google::protobuf::Message {
 public:
  DeviceUnlinked();
  virtual ~DeviceUnlinked();
  
  DeviceUnlinked(const DeviceUnlinked& from);
  
  inline DeviceUnlinked& operator=(const DeviceUnlinked& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const DeviceUnlinked& default_instance();
  
  void Swap(DeviceUnlinked* other);
  
  // implements Message ----------------------------------------------
  
  DeviceUnlinked* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DeviceUnlinked& from);
  void MergeFrom(const DeviceUnlinked& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required fixed64 recipient_uid = 1;
  inline bool has_recipient_uid() const;
  inline void clear_recipient_uid();
  static const int kRecipientUidFieldNumber = 1;
  inline ::google::protobuf::uint64 recipient_uid() const;
  inline void set_recipient_uid(::google::protobuf::uint64 value);
  
  // required fixed64 device_id = 2;
  inline bool has_device_id() const;
  inline void clear_device_id();
  static const int kDeviceIdFieldNumber = 2;
  inline ::google::protobuf::uint64 device_id() const;
  inline void set_device_id(::google::protobuf::uint64 value);
  
  // @@protoc_insertion_point(class_scope:vplex.syncagent.notifier.DeviceUnlinked)
 private:
  inline void set_has_recipient_uid();
  inline void clear_has_recipient_uid();
  inline void set_has_device_id();
  inline void clear_has_device_id();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint64 recipient_uid_;
  ::google::protobuf::uint64 device_id_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_vplex_5fsync_5fagent_5fnotifier_2eproto();
  friend void protobuf_AssignDesc_vplex_5fsync_5fagent_5fnotifier_2eproto();
  friend void protobuf_ShutdownFile_vplex_5fsync_5fagent_5fnotifier_2eproto();
  
  void InitAsDefaultInstance();
  static DeviceUnlinked* default_instance_;
};
// -------------------------------------------------------------------

class DeviceLinked : public ::google::protobuf::Message {
 public:
  DeviceLinked();
  virtual ~DeviceLinked();
  
  DeviceLinked(const DeviceLinked& from);
  
  inline DeviceLinked& operator=(const DeviceLinked& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const DeviceLinked& default_instance();
  
  void Swap(DeviceLinked* other);
  
  // implements Message ----------------------------------------------
  
  DeviceLinked* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DeviceLinked& from);
  void MergeFrom(const DeviceLinked& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required fixed64 recipient_uid = 1;
  inline bool has_recipient_uid() const;
  inline void clear_recipient_uid();
  static const int kRecipientUidFieldNumber = 1;
  inline ::google::protobuf::uint64 recipient_uid() const;
  inline void set_recipient_uid(::google::protobuf::uint64 value);
  
  // required fixed64 device_id = 2;
  inline bool has_device_id() const;
  inline void clear_device_id();
  static const int kDeviceIdFieldNumber = 2;
  inline ::google::protobuf::uint64 device_id() const;
  inline void set_device_id(::google::protobuf::uint64 value);
  
  // @@protoc_insertion_point(class_scope:vplex.syncagent.notifier.DeviceLinked)
 private:
  inline void set_has_recipient_uid();
  inline void clear_has_recipient_uid();
  inline void set_has_device_id();
  inline void clear_has_device_id();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint64 recipient_uid_;
  ::google::protobuf::uint64 device_id_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_vplex_5fsync_5fagent_5fnotifier_2eproto();
  friend void protobuf_AssignDesc_vplex_5fsync_5fagent_5fnotifier_2eproto();
  friend void protobuf_ShutdownFile_vplex_5fsync_5fagent_5fnotifier_2eproto();
  
  void InitAsDefaultInstance();
  static DeviceLinked* default_instance_;
};
// -------------------------------------------------------------------

class DeviceUpdate : public ::google::protobuf::Message {
 public:
  DeviceUpdate();
  virtual ~DeviceUpdate();
  
  DeviceUpdate(const DeviceUpdate& from);
  
  inline DeviceUpdate& operator=(const DeviceUpdate& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const DeviceUpdate& default_instance();
  
  void Swap(DeviceUpdate* other);
  
  // implements Message ----------------------------------------------
  
  DeviceUpdate* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DeviceUpdate& from);
  void MergeFrom(const DeviceUpdate& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required fixed64 recipient_uid = 1;
  inline bool has_recipient_uid() const;
  inline void clear_recipient_uid();
  static const int kRecipientUidFieldNumber = 1;
  inline ::google::protobuf::uint64 recipient_uid() const;
  inline void set_recipient_uid(::google::protobuf::uint64 value);
  
  // required fixed64 device_id = 2;
  inline bool has_device_id() const;
  inline void clear_device_id();
  static const int kDeviceIdFieldNumber = 2;
  inline ::google::protobuf::uint64 device_id() const;
  inline void set_device_id(::google::protobuf::uint64 value);
  
  // @@protoc_insertion_point(class_scope:vplex.syncagent.notifier.DeviceUpdate)
 private:
  inline void set_has_recipient_uid();
  inline void clear_has_recipient_uid();
  inline void set_has_device_id();
  inline void clear_has_device_id();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint64 recipient_uid_;
  ::google::protobuf::uint64 device_id_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_vplex_5fsync_5fagent_5fnotifier_2eproto();
  friend void protobuf_AssignDesc_vplex_5fsync_5fagent_5fnotifier_2eproto();
  friend void protobuf_ShutdownFile_vplex_5fsync_5fagent_5fnotifier_2eproto();
  
  void InitAsDefaultInstance();
  static DeviceUpdate* default_instance_;
};
// -------------------------------------------------------------------

class PSNConnectionUpdate : public ::google::protobuf::Message {
 public:
  PSNConnectionUpdate();
  virtual ~PSNConnectionUpdate();
  
  PSNConnectionUpdate(const PSNConnectionUpdate& from);
  
  inline PSNConnectionUpdate& operator=(const PSNConnectionUpdate& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const PSNConnectionUpdate& default_instance();
  
  void Swap(PSNConnectionUpdate* other);
  
  // implements Message ----------------------------------------------
  
  PSNConnectionUpdate* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PSNConnectionUpdate& from);
  void MergeFrom(const PSNConnectionUpdate& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required fixed64 recipient_uid = 1;
  inline bool has_recipient_uid() const;
  inline void clear_recipient_uid();
  static const int kRecipientUidFieldNumber = 1;
  inline ::google::protobuf::uint64 recipient_uid() const;
  inline void set_recipient_uid(::google::protobuf::uint64 value);
  
  // required fixed64 cluster_id = 2;
  inline bool has_cluster_id() const;
  inline void clear_cluster_id();
  static const int kClusterIdFieldNumber = 2;
  inline ::google::protobuf::uint64 cluster_id() const;
  inline void set_cluster_id(::google::protobuf::uint64 value);
  
  // @@protoc_insertion_point(class_scope:vplex.syncagent.notifier.PSNConnectionUpdate)
 private:
  inline void set_has_recipient_uid();
  inline void clear_has_recipient_uid();
  inline void set_has_cluster_id();
  inline void clear_has_cluster_id();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint64 recipient_uid_;
  ::google::protobuf::uint64 cluster_id_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_vplex_5fsync_5fagent_5fnotifier_2eproto();
  friend void protobuf_AssignDesc_vplex_5fsync_5fagent_5fnotifier_2eproto();
  friend void protobuf_ShutdownFile_vplex_5fsync_5fagent_5fnotifier_2eproto();
  
  void InitAsDefaultInstance();
  static PSNConnectionUpdate* default_instance_;
};
// -------------------------------------------------------------------

class UserStorageUpdate : public ::google::protobuf::Message {
 public:
  UserStorageUpdate();
  virtual ~UserStorageUpdate();
  
  UserStorageUpdate(const UserStorageUpdate& from);
  
  inline UserStorageUpdate& operator=(const UserStorageUpdate& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const UserStorageUpdate& default_instance();
  
  void Swap(UserStorageUpdate* other);
  
  // implements Message ----------------------------------------------
  
  UserStorageUpdate* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UserStorageUpdate& from);
  void MergeFrom(const UserStorageUpdate& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required fixed64 recipient_uid = 1;
  inline bool has_recipient_uid() const;
  inline void clear_recipient_uid();
  static const int kRecipientUidFieldNumber = 1;
  inline ::google::protobuf::uint64 recipient_uid() const;
  inline void set_recipient_uid(::google::protobuf::uint64 value);
  
  // @@protoc_insertion_point(class_scope:vplex.syncagent.notifier.UserStorageUpdate)
 private:
  inline void set_has_recipient_uid();
  inline void clear_has_recipient_uid();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint64 recipient_uid_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_vplex_5fsync_5fagent_5fnotifier_2eproto();
  friend void protobuf_AssignDesc_vplex_5fsync_5fagent_5fnotifier_2eproto();
  friend void protobuf_ShutdownFile_vplex_5fsync_5fagent_5fnotifier_2eproto();
  
  void InitAsDefaultInstance();
  static UserStorageUpdate* default_instance_;
};
// -------------------------------------------------------------------

class SyncAgentNotification : public ::google::protobuf::Message {
 public:
  SyncAgentNotification();
  virtual ~SyncAgentNotification();
  
  SyncAgentNotification(const SyncAgentNotification& from);
  
  inline SyncAgentNotification& operator=(const SyncAgentNotification& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SyncAgentNotification& default_instance();
  
  void Swap(SyncAgentNotification* other);
  
  // implements Message ----------------------------------------------
  
  SyncAgentNotification* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SyncAgentNotification& from);
  void MergeFrom(const SyncAgentNotification& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated .vplex.syncagent.notifier.UserStorageUpdate user_storage_update = 1;
  inline int user_storage_update_size() const;
  inline void clear_user_storage_update();
  static const int kUserStorageUpdateFieldNumber = 1;
  inline const ::vplex::syncagent::notifier::UserStorageUpdate& user_storage_update(int index) const;
  inline ::vplex::syncagent::notifier::UserStorageUpdate* mutable_user_storage_update(int index);
  inline ::vplex::syncagent::notifier::UserStorageUpdate* add_user_storage_update();
  inline const ::google::protobuf::RepeatedPtrField< ::vplex::syncagent::notifier::UserStorageUpdate >&
      user_storage_update() const;
  inline ::google::protobuf::RepeatedPtrField< ::vplex::syncagent::notifier::UserStorageUpdate >*
      mutable_user_storage_update();
  
  // repeated .vplex.syncagent.notifier.DatasetUpdate dataset_update = 2;
  inline int dataset_update_size() const;
  inline void clear_dataset_update();
  static const int kDatasetUpdateFieldNumber = 2;
  inline const ::vplex::syncagent::notifier::DatasetUpdate& dataset_update(int index) const;
  inline ::vplex::syncagent::notifier::DatasetUpdate* mutable_dataset_update(int index);
  inline ::vplex::syncagent::notifier::DatasetUpdate* add_dataset_update();
  inline const ::google::protobuf::RepeatedPtrField< ::vplex::syncagent::notifier::DatasetUpdate >&
      dataset_update() const;
  inline ::google::protobuf::RepeatedPtrField< ::vplex::syncagent::notifier::DatasetUpdate >*
      mutable_dataset_update();
  
  // repeated .vplex.syncagent.notifier.DatasetContentUpdate dataset_content_update = 3;
  inline int dataset_content_update_size() const;
  inline void clear_dataset_content_update();
  static const int kDatasetContentUpdateFieldNumber = 3;
  inline const ::vplex::syncagent::notifier::DatasetContentUpdate& dataset_content_update(int index) const;
  inline ::vplex::syncagent::notifier::DatasetContentUpdate* mutable_dataset_content_update(int index);
  inline ::vplex::syncagent::notifier::DatasetContentUpdate* add_dataset_content_update();
  inline const ::google::protobuf::RepeatedPtrField< ::vplex::syncagent::notifier::DatasetContentUpdate >&
      dataset_content_update() const;
  inline ::google::protobuf::RepeatedPtrField< ::vplex::syncagent::notifier::DatasetContentUpdate >*
      mutable_dataset_content_update();
  
  // repeated .vplex.syncagent.notifier.SubscriptionUpdate subscription_update = 4;
  inline int subscription_update_size() const;
  inline void clear_subscription_update();
  static const int kSubscriptionUpdateFieldNumber = 4;
  inline const ::vplex::syncagent::notifier::SubscriptionUpdate& subscription_update(int index) const;
  inline ::vplex::syncagent::notifier::SubscriptionUpdate* mutable_subscription_update(int index);
  inline ::vplex::syncagent::notifier::SubscriptionUpdate* add_subscription_update();
  inline const ::google::protobuf::RepeatedPtrField< ::vplex::syncagent::notifier::SubscriptionUpdate >&
      subscription_update() const;
  inline ::google::protobuf::RepeatedPtrField< ::vplex::syncagent::notifier::SubscriptionUpdate >*
      mutable_subscription_update();
  
  // repeated .vplex.syncagent.notifier.DeviceUnlinked device_unlinked = 5;
  inline int device_unlinked_size() const;
  inline void clear_device_unlinked();
  static const int kDeviceUnlinkedFieldNumber = 5;
  inline const ::vplex::syncagent::notifier::DeviceUnlinked& device_unlinked(int index) const;
  inline ::vplex::syncagent::notifier::DeviceUnlinked* mutable_device_unlinked(int index);
  inline ::vplex::syncagent::notifier::DeviceUnlinked* add_device_unlinked();
  inline const ::google::protobuf::RepeatedPtrField< ::vplex::syncagent::notifier::DeviceUnlinked >&
      device_unlinked() const;
  inline ::google::protobuf::RepeatedPtrField< ::vplex::syncagent::notifier::DeviceUnlinked >*
      mutable_device_unlinked();
  
  // repeated .vplex.syncagent.notifier.PSNConnectionUpdate psn_connection_update = 6;
  inline int psn_connection_update_size() const;
  inline void clear_psn_connection_update();
  static const int kPsnConnectionUpdateFieldNumber = 6;
  inline const ::vplex::syncagent::notifier::PSNConnectionUpdate& psn_connection_update(int index) const;
  inline ::vplex::syncagent::notifier::PSNConnectionUpdate* mutable_psn_connection_update(int index);
  inline ::vplex::syncagent::notifier::PSNConnectionUpdate* add_psn_connection_update();
  inline const ::google::protobuf::RepeatedPtrField< ::vplex::syncagent::notifier::PSNConnectionUpdate >&
      psn_connection_update() const;
  inline ::google::protobuf::RepeatedPtrField< ::vplex::syncagent::notifier::PSNConnectionUpdate >*
      mutable_psn_connection_update();
  
  // repeated .vplex.syncagent.notifier.DeviceLinked device_linked = 7;
  inline int device_linked_size() const;
  inline void clear_device_linked();
  static const int kDeviceLinkedFieldNumber = 7;
  inline const ::vplex::syncagent::notifier::DeviceLinked& device_linked(int index) const;
  inline ::vplex::syncagent::notifier::DeviceLinked* mutable_device_linked(int index);
  inline ::vplex::syncagent::notifier::DeviceLinked* add_device_linked();
  inline const ::google::protobuf::RepeatedPtrField< ::vplex::syncagent::notifier::DeviceLinked >&
      device_linked() const;
  inline ::google::protobuf::RepeatedPtrField< ::vplex::syncagent::notifier::DeviceLinked >*
      mutable_device_linked();
  
  // repeated .vplex.syncagent.notifier.DeviceUpdate device_update = 8;
  inline int device_update_size() const;
  inline void clear_device_update();
  static const int kDeviceUpdateFieldNumber = 8;
  inline const ::vplex::syncagent::notifier::DeviceUpdate& device_update(int index) const;
  inline ::vplex::syncagent::notifier::DeviceUpdate* mutable_device_update(int index);
  inline ::vplex::syncagent::notifier::DeviceUpdate* add_device_update();
  inline const ::google::protobuf::RepeatedPtrField< ::vplex::syncagent::notifier::DeviceUpdate >&
      device_update() const;
  inline ::google::protobuf::RepeatedPtrField< ::vplex::syncagent::notifier::DeviceUpdate >*
      mutable_device_update();
  
  // @@protoc_insertion_point(class_scope:vplex.syncagent.notifier.SyncAgentNotification)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::vplex::syncagent::notifier::UserStorageUpdate > user_storage_update_;
  ::google::protobuf::RepeatedPtrField< ::vplex::syncagent::notifier::DatasetUpdate > dataset_update_;
  ::google::protobuf::RepeatedPtrField< ::vplex::syncagent::notifier::DatasetContentUpdate > dataset_content_update_;
  ::google::protobuf::RepeatedPtrField< ::vplex::syncagent::notifier::SubscriptionUpdate > subscription_update_;
  ::google::protobuf::RepeatedPtrField< ::vplex::syncagent::notifier::DeviceUnlinked > device_unlinked_;
  ::google::protobuf::RepeatedPtrField< ::vplex::syncagent::notifier::PSNConnectionUpdate > psn_connection_update_;
  ::google::protobuf::RepeatedPtrField< ::vplex::syncagent::notifier::DeviceLinked > device_linked_;
  ::google::protobuf::RepeatedPtrField< ::vplex::syncagent::notifier::DeviceUpdate > device_update_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(8 + 31) / 32];
  
  friend void  protobuf_AddDesc_vplex_5fsync_5fagent_5fnotifier_2eproto();
  friend void protobuf_AssignDesc_vplex_5fsync_5fagent_5fnotifier_2eproto();
  friend void protobuf_ShutdownFile_vplex_5fsync_5fagent_5fnotifier_2eproto();
  
  void InitAsDefaultInstance();
  static SyncAgentNotification* default_instance_;
};
// ===================================================================


// ===================================================================

// DatasetUpdate

// required fixed64 recipient_uid = 1;
inline bool DatasetUpdate::has_recipient_uid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DatasetUpdate::set_has_recipient_uid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DatasetUpdate::clear_has_recipient_uid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DatasetUpdate::clear_recipient_uid() {
  recipient_uid_ = GOOGLE_ULONGLONG(0);
  clear_has_recipient_uid();
}
inline ::google::protobuf::uint64 DatasetUpdate::recipient_uid() const {
  return recipient_uid_;
}
inline void DatasetUpdate::set_recipient_uid(::google::protobuf::uint64 value) {
  set_has_recipient_uid();
  recipient_uid_ = value;
}

// required fixed64 dataset_id = 2;
inline bool DatasetUpdate::has_dataset_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DatasetUpdate::set_has_dataset_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DatasetUpdate::clear_has_dataset_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DatasetUpdate::clear_dataset_id() {
  dataset_id_ = GOOGLE_ULONGLONG(0);
  clear_has_dataset_id();
}
inline ::google::protobuf::uint64 DatasetUpdate::dataset_id() const {
  return dataset_id_;
}
inline void DatasetUpdate::set_dataset_id(::google::protobuf::uint64 value) {
  set_has_dataset_id();
  dataset_id_ = value;
}

// -------------------------------------------------------------------

// DatasetContentUpdate

// required fixed64 recipient_uid = 1;
inline bool DatasetContentUpdate::has_recipient_uid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DatasetContentUpdate::set_has_recipient_uid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DatasetContentUpdate::clear_has_recipient_uid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DatasetContentUpdate::clear_recipient_uid() {
  recipient_uid_ = GOOGLE_ULONGLONG(0);
  clear_has_recipient_uid();
}
inline ::google::protobuf::uint64 DatasetContentUpdate::recipient_uid() const {
  return recipient_uid_;
}
inline void DatasetContentUpdate::set_recipient_uid(::google::protobuf::uint64 value) {
  set_has_recipient_uid();
  recipient_uid_ = value;
}

// required fixed64 dataset_id = 2;
inline bool DatasetContentUpdate::has_dataset_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DatasetContentUpdate::set_has_dataset_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DatasetContentUpdate::clear_has_dataset_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DatasetContentUpdate::clear_dataset_id() {
  dataset_id_ = GOOGLE_ULONGLONG(0);
  clear_has_dataset_id();
}
inline ::google::protobuf::uint64 DatasetContentUpdate::dataset_id() const {
  return dataset_id_;
}
inline void DatasetContentUpdate::set_dataset_id(::google::protobuf::uint64 value) {
  set_has_dataset_id();
  dataset_id_ = value;
}

// -------------------------------------------------------------------

// SubscriptionUpdate

// required fixed64 recipient_uid = 1;
inline bool SubscriptionUpdate::has_recipient_uid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SubscriptionUpdate::set_has_recipient_uid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SubscriptionUpdate::clear_has_recipient_uid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SubscriptionUpdate::clear_recipient_uid() {
  recipient_uid_ = GOOGLE_ULONGLONG(0);
  clear_has_recipient_uid();
}
inline ::google::protobuf::uint64 SubscriptionUpdate::recipient_uid() const {
  return recipient_uid_;
}
inline void SubscriptionUpdate::set_recipient_uid(::google::protobuf::uint64 value) {
  set_has_recipient_uid();
  recipient_uid_ = value;
}

// required fixed64 device_id = 2;
inline bool SubscriptionUpdate::has_device_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SubscriptionUpdate::set_has_device_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SubscriptionUpdate::clear_has_device_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SubscriptionUpdate::clear_device_id() {
  device_id_ = GOOGLE_ULONGLONG(0);
  clear_has_device_id();
}
inline ::google::protobuf::uint64 SubscriptionUpdate::device_id() const {
  return device_id_;
}
inline void SubscriptionUpdate::set_device_id(::google::protobuf::uint64 value) {
  set_has_device_id();
  device_id_ = value;
}

// required fixed64 dataset_id = 3;
inline bool SubscriptionUpdate::has_dataset_id() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SubscriptionUpdate::set_has_dataset_id() {
  _has_bits_[0] |= 0x00000004u;
}
inline void SubscriptionUpdate::clear_has_dataset_id() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void SubscriptionUpdate::clear_dataset_id() {
  dataset_id_ = GOOGLE_ULONGLONG(0);
  clear_has_dataset_id();
}
inline ::google::protobuf::uint64 SubscriptionUpdate::dataset_id() const {
  return dataset_id_;
}
inline void SubscriptionUpdate::set_dataset_id(::google::protobuf::uint64 value) {
  set_has_dataset_id();
  dataset_id_ = value;
}

// -------------------------------------------------------------------

// DeviceUnlinked

// required fixed64 recipient_uid = 1;
inline bool DeviceUnlinked::has_recipient_uid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DeviceUnlinked::set_has_recipient_uid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DeviceUnlinked::clear_has_recipient_uid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DeviceUnlinked::clear_recipient_uid() {
  recipient_uid_ = GOOGLE_ULONGLONG(0);
  clear_has_recipient_uid();
}
inline ::google::protobuf::uint64 DeviceUnlinked::recipient_uid() const {
  return recipient_uid_;
}
inline void DeviceUnlinked::set_recipient_uid(::google::protobuf::uint64 value) {
  set_has_recipient_uid();
  recipient_uid_ = value;
}

// required fixed64 device_id = 2;
inline bool DeviceUnlinked::has_device_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DeviceUnlinked::set_has_device_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DeviceUnlinked::clear_has_device_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DeviceUnlinked::clear_device_id() {
  device_id_ = GOOGLE_ULONGLONG(0);
  clear_has_device_id();
}
inline ::google::protobuf::uint64 DeviceUnlinked::device_id() const {
  return device_id_;
}
inline void DeviceUnlinked::set_device_id(::google::protobuf::uint64 value) {
  set_has_device_id();
  device_id_ = value;
}

// -------------------------------------------------------------------

// DeviceLinked

// required fixed64 recipient_uid = 1;
inline bool DeviceLinked::has_recipient_uid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DeviceLinked::set_has_recipient_uid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DeviceLinked::clear_has_recipient_uid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DeviceLinked::clear_recipient_uid() {
  recipient_uid_ = GOOGLE_ULONGLONG(0);
  clear_has_recipient_uid();
}
inline ::google::protobuf::uint64 DeviceLinked::recipient_uid() const {
  return recipient_uid_;
}
inline void DeviceLinked::set_recipient_uid(::google::protobuf::uint64 value) {
  set_has_recipient_uid();
  recipient_uid_ = value;
}

// required fixed64 device_id = 2;
inline bool DeviceLinked::has_device_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DeviceLinked::set_has_device_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DeviceLinked::clear_has_device_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DeviceLinked::clear_device_id() {
  device_id_ = GOOGLE_ULONGLONG(0);
  clear_has_device_id();
}
inline ::google::protobuf::uint64 DeviceLinked::device_id() const {
  return device_id_;
}
inline void DeviceLinked::set_device_id(::google::protobuf::uint64 value) {
  set_has_device_id();
  device_id_ = value;
}

// -------------------------------------------------------------------

// DeviceUpdate

// required fixed64 recipient_uid = 1;
inline bool DeviceUpdate::has_recipient_uid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DeviceUpdate::set_has_recipient_uid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DeviceUpdate::clear_has_recipient_uid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DeviceUpdate::clear_recipient_uid() {
  recipient_uid_ = GOOGLE_ULONGLONG(0);
  clear_has_recipient_uid();
}
inline ::google::protobuf::uint64 DeviceUpdate::recipient_uid() const {
  return recipient_uid_;
}
inline void DeviceUpdate::set_recipient_uid(::google::protobuf::uint64 value) {
  set_has_recipient_uid();
  recipient_uid_ = value;
}

// required fixed64 device_id = 2;
inline bool DeviceUpdate::has_device_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DeviceUpdate::set_has_device_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DeviceUpdate::clear_has_device_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DeviceUpdate::clear_device_id() {
  device_id_ = GOOGLE_ULONGLONG(0);
  clear_has_device_id();
}
inline ::google::protobuf::uint64 DeviceUpdate::device_id() const {
  return device_id_;
}
inline void DeviceUpdate::set_device_id(::google::protobuf::uint64 value) {
  set_has_device_id();
  device_id_ = value;
}

// -------------------------------------------------------------------

// PSNConnectionUpdate

// required fixed64 recipient_uid = 1;
inline bool PSNConnectionUpdate::has_recipient_uid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PSNConnectionUpdate::set_has_recipient_uid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PSNConnectionUpdate::clear_has_recipient_uid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PSNConnectionUpdate::clear_recipient_uid() {
  recipient_uid_ = GOOGLE_ULONGLONG(0);
  clear_has_recipient_uid();
}
inline ::google::protobuf::uint64 PSNConnectionUpdate::recipient_uid() const {
  return recipient_uid_;
}
inline void PSNConnectionUpdate::set_recipient_uid(::google::protobuf::uint64 value) {
  set_has_recipient_uid();
  recipient_uid_ = value;
}

// required fixed64 cluster_id = 2;
inline bool PSNConnectionUpdate::has_cluster_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PSNConnectionUpdate::set_has_cluster_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PSNConnectionUpdate::clear_has_cluster_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PSNConnectionUpdate::clear_cluster_id() {
  cluster_id_ = GOOGLE_ULONGLONG(0);
  clear_has_cluster_id();
}
inline ::google::protobuf::uint64 PSNConnectionUpdate::cluster_id() const {
  return cluster_id_;
}
inline void PSNConnectionUpdate::set_cluster_id(::google::protobuf::uint64 value) {
  set_has_cluster_id();
  cluster_id_ = value;
}

// -------------------------------------------------------------------

// UserStorageUpdate

// required fixed64 recipient_uid = 1;
inline bool UserStorageUpdate::has_recipient_uid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UserStorageUpdate::set_has_recipient_uid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UserStorageUpdate::clear_has_recipient_uid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UserStorageUpdate::clear_recipient_uid() {
  recipient_uid_ = GOOGLE_ULONGLONG(0);
  clear_has_recipient_uid();
}
inline ::google::protobuf::uint64 UserStorageUpdate::recipient_uid() const {
  return recipient_uid_;
}
inline void UserStorageUpdate::set_recipient_uid(::google::protobuf::uint64 value) {
  set_has_recipient_uid();
  recipient_uid_ = value;
}

// -------------------------------------------------------------------

// SyncAgentNotification

// repeated .vplex.syncagent.notifier.UserStorageUpdate user_storage_update = 1;
inline int SyncAgentNotification::user_storage_update_size() const {
  return user_storage_update_.size();
}
inline void SyncAgentNotification::clear_user_storage_update() {
  user_storage_update_.Clear();
}
inline const ::vplex::syncagent::notifier::UserStorageUpdate& SyncAgentNotification::user_storage_update(int index) const {
  return user_storage_update_.Get(index);
}
inline ::vplex::syncagent::notifier::UserStorageUpdate* SyncAgentNotification::mutable_user_storage_update(int index) {
  return user_storage_update_.Mutable(index);
}
inline ::vplex::syncagent::notifier::UserStorageUpdate* SyncAgentNotification::add_user_storage_update() {
  return user_storage_update_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::vplex::syncagent::notifier::UserStorageUpdate >&
SyncAgentNotification::user_storage_update() const {
  return user_storage_update_;
}
inline ::google::protobuf::RepeatedPtrField< ::vplex::syncagent::notifier::UserStorageUpdate >*
SyncAgentNotification::mutable_user_storage_update() {
  return &user_storage_update_;
}

// repeated .vplex.syncagent.notifier.DatasetUpdate dataset_update = 2;
inline int SyncAgentNotification::dataset_update_size() const {
  return dataset_update_.size();
}
inline void SyncAgentNotification::clear_dataset_update() {
  dataset_update_.Clear();
}
inline const ::vplex::syncagent::notifier::DatasetUpdate& SyncAgentNotification::dataset_update(int index) const {
  return dataset_update_.Get(index);
}
inline ::vplex::syncagent::notifier::DatasetUpdate* SyncAgentNotification::mutable_dataset_update(int index) {
  return dataset_update_.Mutable(index);
}
inline ::vplex::syncagent::notifier::DatasetUpdate* SyncAgentNotification::add_dataset_update() {
  return dataset_update_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::vplex::syncagent::notifier::DatasetUpdate >&
SyncAgentNotification::dataset_update() const {
  return dataset_update_;
}
inline ::google::protobuf::RepeatedPtrField< ::vplex::syncagent::notifier::DatasetUpdate >*
SyncAgentNotification::mutable_dataset_update() {
  return &dataset_update_;
}

// repeated .vplex.syncagent.notifier.DatasetContentUpdate dataset_content_update = 3;
inline int SyncAgentNotification::dataset_content_update_size() const {
  return dataset_content_update_.size();
}
inline void SyncAgentNotification::clear_dataset_content_update() {
  dataset_content_update_.Clear();
}
inline const ::vplex::syncagent::notifier::DatasetContentUpdate& SyncAgentNotification::dataset_content_update(int index) const {
  return dataset_content_update_.Get(index);
}
inline ::vplex::syncagent::notifier::DatasetContentUpdate* SyncAgentNotification::mutable_dataset_content_update(int index) {
  return dataset_content_update_.Mutable(index);
}
inline ::vplex::syncagent::notifier::DatasetContentUpdate* SyncAgentNotification::add_dataset_content_update() {
  return dataset_content_update_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::vplex::syncagent::notifier::DatasetContentUpdate >&
SyncAgentNotification::dataset_content_update() const {
  return dataset_content_update_;
}
inline ::google::protobuf::RepeatedPtrField< ::vplex::syncagent::notifier::DatasetContentUpdate >*
SyncAgentNotification::mutable_dataset_content_update() {
  return &dataset_content_update_;
}

// repeated .vplex.syncagent.notifier.SubscriptionUpdate subscription_update = 4;
inline int SyncAgentNotification::subscription_update_size() const {
  return subscription_update_.size();
}
inline void SyncAgentNotification::clear_subscription_update() {
  subscription_update_.Clear();
}
inline const ::vplex::syncagent::notifier::SubscriptionUpdate& SyncAgentNotification::subscription_update(int index) const {
  return subscription_update_.Get(index);
}
inline ::vplex::syncagent::notifier::SubscriptionUpdate* SyncAgentNotification::mutable_subscription_update(int index) {
  return subscription_update_.Mutable(index);
}
inline ::vplex::syncagent::notifier::SubscriptionUpdate* SyncAgentNotification::add_subscription_update() {
  return subscription_update_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::vplex::syncagent::notifier::SubscriptionUpdate >&
SyncAgentNotification::subscription_update() const {
  return subscription_update_;
}
inline ::google::protobuf::RepeatedPtrField< ::vplex::syncagent::notifier::SubscriptionUpdate >*
SyncAgentNotification::mutable_subscription_update() {
  return &subscription_update_;
}

// repeated .vplex.syncagent.notifier.DeviceUnlinked device_unlinked = 5;
inline int SyncAgentNotification::device_unlinked_size() const {
  return device_unlinked_.size();
}
inline void SyncAgentNotification::clear_device_unlinked() {
  device_unlinked_.Clear();
}
inline const ::vplex::syncagent::notifier::DeviceUnlinked& SyncAgentNotification::device_unlinked(int index) const {
  return device_unlinked_.Get(index);
}
inline ::vplex::syncagent::notifier::DeviceUnlinked* SyncAgentNotification::mutable_device_unlinked(int index) {
  return device_unlinked_.Mutable(index);
}
inline ::vplex::syncagent::notifier::DeviceUnlinked* SyncAgentNotification::add_device_unlinked() {
  return device_unlinked_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::vplex::syncagent::notifier::DeviceUnlinked >&
SyncAgentNotification::device_unlinked() const {
  return device_unlinked_;
}
inline ::google::protobuf::RepeatedPtrField< ::vplex::syncagent::notifier::DeviceUnlinked >*
SyncAgentNotification::mutable_device_unlinked() {
  return &device_unlinked_;
}

// repeated .vplex.syncagent.notifier.PSNConnectionUpdate psn_connection_update = 6;
inline int SyncAgentNotification::psn_connection_update_size() const {
  return psn_connection_update_.size();
}
inline void SyncAgentNotification::clear_psn_connection_update() {
  psn_connection_update_.Clear();
}
inline const ::vplex::syncagent::notifier::PSNConnectionUpdate& SyncAgentNotification::psn_connection_update(int index) const {
  return psn_connection_update_.Get(index);
}
inline ::vplex::syncagent::notifier::PSNConnectionUpdate* SyncAgentNotification::mutable_psn_connection_update(int index) {
  return psn_connection_update_.Mutable(index);
}
inline ::vplex::syncagent::notifier::PSNConnectionUpdate* SyncAgentNotification::add_psn_connection_update() {
  return psn_connection_update_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::vplex::syncagent::notifier::PSNConnectionUpdate >&
SyncAgentNotification::psn_connection_update() const {
  return psn_connection_update_;
}
inline ::google::protobuf::RepeatedPtrField< ::vplex::syncagent::notifier::PSNConnectionUpdate >*
SyncAgentNotification::mutable_psn_connection_update() {
  return &psn_connection_update_;
}

// repeated .vplex.syncagent.notifier.DeviceLinked device_linked = 7;
inline int SyncAgentNotification::device_linked_size() const {
  return device_linked_.size();
}
inline void SyncAgentNotification::clear_device_linked() {
  device_linked_.Clear();
}
inline const ::vplex::syncagent::notifier::DeviceLinked& SyncAgentNotification::device_linked(int index) const {
  return device_linked_.Get(index);
}
inline ::vplex::syncagent::notifier::DeviceLinked* SyncAgentNotification::mutable_device_linked(int index) {
  return device_linked_.Mutable(index);
}
inline ::vplex::syncagent::notifier::DeviceLinked* SyncAgentNotification::add_device_linked() {
  return device_linked_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::vplex::syncagent::notifier::DeviceLinked >&
SyncAgentNotification::device_linked() const {
  return device_linked_;
}
inline ::google::protobuf::RepeatedPtrField< ::vplex::syncagent::notifier::DeviceLinked >*
SyncAgentNotification::mutable_device_linked() {
  return &device_linked_;
}

// repeated .vplex.syncagent.notifier.DeviceUpdate device_update = 8;
inline int SyncAgentNotification::device_update_size() const {
  return device_update_.size();
}
inline void SyncAgentNotification::clear_device_update() {
  device_update_.Clear();
}
inline const ::vplex::syncagent::notifier::DeviceUpdate& SyncAgentNotification::device_update(int index) const {
  return device_update_.Get(index);
}
inline ::vplex::syncagent::notifier::DeviceUpdate* SyncAgentNotification::mutable_device_update(int index) {
  return device_update_.Mutable(index);
}
inline ::vplex::syncagent::notifier::DeviceUpdate* SyncAgentNotification::add_device_update() {
  return device_update_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::vplex::syncagent::notifier::DeviceUpdate >&
SyncAgentNotification::device_update() const {
  return device_update_;
}
inline ::google::protobuf::RepeatedPtrField< ::vplex::syncagent::notifier::DeviceUpdate >*
SyncAgentNotification::mutable_device_update() {
  return &device_update_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace notifier
}  // namespace syncagent
}  // namespace vplex

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_vplex_5fsync_5fagent_5fnotifier_2eproto__INCLUDED
