// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vplex_community_types.proto

#ifndef PROTOBUF_vplex_5fcommunity_5ftypes_2eproto__INCLUDED
#define PROTOBUF_vplex_5fcommunity_5ftypes_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace vplex {
namespace community {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_vplex_5fcommunity_5ftypes_2eproto();
void protobuf_AssignDesc_vplex_5fcommunity_5ftypes_2eproto();
void protobuf_ShutdownFile_vplex_5fcommunity_5ftypes_2eproto();


enum OnlineState_t {
  OFFLINE = 0,
  AVAILABLE = 1,
  AWAY = 3,
  IDLE = 4,
  INVISIBLE = 5
};
bool OnlineState_t_IsValid(int value);
const OnlineState_t OnlineState_t_MIN = OFFLINE;
const OnlineState_t OnlineState_t_MAX = INVISIBLE;
const int OnlineState_t_ARRAYSIZE = OnlineState_t_MAX + 1;

const ::google::protobuf::EnumDescriptor* OnlineState_t_descriptor();
inline const ::std::string& OnlineState_t_Name(OnlineState_t value) {
  return ::google::protobuf::internal::NameOfEnum(
    OnlineState_t_descriptor(), value);
}
inline bool OnlineState_t_Parse(
    const ::std::string& name, OnlineState_t* value) {
  return ::google::protobuf::internal::ParseNamedEnum<OnlineState_t>(
    OnlineState_t_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

}  // namespace community
}  // namespace vplex

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< vplex::community::OnlineState_t>() {
  return vplex::community::OnlineState_t_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_vplex_5fcommunity_5ftypes_2eproto__INCLUDED
