// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "vplex_community_types.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace vplex {
namespace community {

namespace {

const ::google::protobuf::EnumDescriptor* OnlineState_t_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_vplex_5fcommunity_5ftypes_2eproto() {
  protobuf_AddDesc_vplex_5fcommunity_5ftypes_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "vplex_community_types.proto");
  GOOGLE_CHECK(file != NULL);
  OnlineState_t_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_vplex_5fcommunity_5ftypes_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_vplex_5fcommunity_5ftypes_2eproto() {
}

void protobuf_AddDesc_vplex_5fcommunity_5ftypes_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\033vplex_community_types.proto\022\017vplex.com"
    "munity*N\n\rOnlineState_t\022\013\n\007OFFLINE\020\000\022\r\n\t"
    "AVAILABLE\020\001\022\010\n\004AWAY\020\003\022\010\n\004IDLE\020\004\022\r\n\tINVIS"
    "IBLE\020\005B!\n\017igware.vplex.pbB\016CommunityType"
    "s", 161);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "vplex_community_types.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_vplex_5fcommunity_5ftypes_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_vplex_5fcommunity_5ftypes_2eproto {
  StaticDescriptorInitializer_vplex_5fcommunity_5ftypes_2eproto() {
    protobuf_AddDesc_vplex_5fcommunity_5ftypes_2eproto();
  }
} static_descriptor_initializer_vplex_5fcommunity_5ftypes_2eproto_;

const ::google::protobuf::EnumDescriptor* OnlineState_t_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return OnlineState_t_descriptor_;
}
bool OnlineState_t_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace community
}  // namespace vplex

// @@protoc_insertion_point(global_scope)
