cpp_binary(
    name = 'syncConfigThreadPoolTest',
    includes = [
        '/gvm_core/internal/sync_config/src'
    ],
    srcs = [
        'syncConfigThreadPoolTest.cpp'
    ],
    deps = [
        '/gvm_core/internal/sync_config:libsync_config',
    ]
)
