cpp_binary(
    name = 'exifBasicTest',
    includes = ['include'],
    srcs = [
            'exifBasicTest.cpp',
           ],
    deps = [
            '/gvm_core/internal/exif_parser:libexif_parser',
            '/gvm_core/vpl:libvplcore',
            '/gvm_core/vplex:libvplexcore',
            '/gvm_core/internal/file_utils:libfile_utils',
           ],
)

