##########
# This is the buildbot test run configuration file for the 'win32_ul' PRODUCT.
##########

##########
# The following section describes reserved configuration variables.
##########
# DB Info
# To prevent upload of results to the database, comment out at least one of these parameters.
TH_DBNAME=testharness_v2
TH_DBHOST=mysql.ctbg.acer.com
TH_DBUSER=testharness
TH_DBPWD=route2me

# Name to use in the database for this run
TH_RUN_NAME=winrt_3.2_against_lab18

# Directory in which to save test run/test case output.
# Results from each suite executed will be saved in a separate directory under this directory
# This can be overridden with the -o testharness command line option.
TH_OUTPUT_DIR=/tmp/testharness/output_winrt_ul

# Name of the file where a summary of the test results is written
# This can be overridden with the -s testharness command line option.
#TH_SUMMARY_FILE=/tmp/testharness/output/testharness_summary.out

# Directory in which to look for test suites.
# Default is the sw_x/tests directory in the same tree as the testharness script.
# This can be overridden with the -t testharness command line option.
#TH_TEST_SUITE_DIR=$WORKDIR/sw_x/tests

# The list of suites to run and the order in which to run them.
TH_SUITE=vpl::timeout=15
TH_SUITE=vplex::timeout=5
TH_SUITE=ts_network::timeout=15
TH_SUITE=sdk_release_basic::timeout=10
TH_SUITE=sdk_release_mediametadata::timeout=15
#TH_SUITE=sdk_release_mediametadata_virt_up_normal_down::timeout=15
TH_SUITE=sdk_release_picstream::timeout=15
TH_SUITE=sdk_release_picstream_index_only::timeout=5
TH_SUITE=sdk_release_clouddoc::timeout=10

##########
# Test-run-level environment variables go here.
# They are set in the execution environment of every test case that is executed in this test run.
##########

# IP/name of the Windows machine to run the tests on
TARGET_USER=build
TARGET_MACHINE=alondonwin8

CCD_TEST_ACCOUNT=TOT_winrtTest@igware.com
CCD_TEST_ACCOUNT_1=TOT_winrtTest_1@igware.com
CCD_TEST_ACCOUNT_2=TOT_winrtTest_2@igware.com

USE_ARCHIVED_BUILD=true

# Lab to execute against
LAB=lab18
LAB_DOMAIN_NAME=pc-int.igware.net
INTERNAL_LAB_DOMAIN_NAME=lab18

# sdk_release_rc_tests settings
DX_TARGET_PLAT=winrt

TEST_MASTER_MACHINE=b21-03
TARGET_WIN32_CLOUDPC=127.0.0.1
TARGET_WIN32_CLIENT=127.0.0.1
TARGET_WIN32_MD=10.50.10.31

TARGET_WINRT_MACHINE=alondonwin8 
TARGET_WINRT_USER=build
TARGET_WINRT_DEVICE_NAME=alondonwin8 

TARGET_USER=build
TARGET_WIN32_CLIENT_USER=build

TARGET_MACHINE_DEVICE_NAME=b21-03
TARGET_WIN32_CLIENT_DEVICE_NAME=b21-03

TARGET_MACHINE_ALIAS=S-1-5-21-871735737-3788125764-673761111-1000
TARGET_WIN32_CLIENT_ALIAS=S-1-5-21-871735737-3788125764-673761111-1011
TARGET_PLATFORM_ALIAS=MD1

CCD_TEST_ACCOUNT_1=TOT_sdk_release_rc_tests_3@acercloud.org
CCD_TEST_ACCOUNT_2=TOT_sdk_release_rc_tests_4@acercloud.org
CCD_TEST_ACCOUNT_PASSWORD=password
IDT_TOOLS=$(SRC_SWI)/tools/idt

# vplex tests settings
VPLTEST_BRANCH="TOT"
