##########
# This is the buildbot test run configuration file for the 'win_desk' PRODUCT.
##########

##########
# The following section describes reserved configuration variables.
##########
# DB Info
# To prevent upload of results to the database, comment out at least one of these parameters.
TH_DBNAME=testharness_v2
TH_DBHOST=mysql.ctbg.acer.com
TH_DBUSER=testharness
TH_DBPWD=route2me

# Name to use in the database for this run
TH_RUN_NAME=win_desk_3.2_onWin7_against_lab16

# Directory in which to save test run/test case output.
# Results from each suite executed will be saved in a separate directory under this directory
# This can be overridden with the -o testharness command line option.
TH_OUTPUT_DIR=/tmp/testharness/output_win_desk_win7

# Name of the file where a summary of the test results is written
# This can be overridden with the -s testharness command line option.
#TH_SUMMARY_FILE=/tmp/testharness/output/testharness_summary.out

# Directory in which to look for test suites.
# Default is the sw_x/tests directory in the same tree as the testharness script.
# This can be overridden with the -t testharness command line option.
#TH_TEST_SUITE_DIR=$WORKDIR/sw_x/tests

# The list of suites to run and the order in which to run them.
TH_SUITE=sync_config::timeout=15
TH_SUITE=sdk_release_basic::timeout=15
TH_SUITE=sdk_release_mediametadata::timeout=20
TH_SUITE=sdk_release_picstream::timeout=20
TH_SUITE=sdk_release_picstream_index_only::timeout=5
TH_SUITE=sdk_release_remotefile::timeout=15
TH_SUITE=sdk_release_clouddoc::timeout=15
TH_SUITE=regression_internal_direct::timeout=15
# this should be at least twice that of regression_proxy_alt_tun
TH_SUITE=regression_proxy::timeout=25

##########
# Test-run-level environment variables go here.
# They are set in the execution environment of every test case that is executed in this test run.
##########

# IP/name of the Windows machine to run the tests on
TARGET_MACHINE1=b19-02
TARGET_MACHINE2=b19-03
TARGET_MACHINE=b19-02
TARGET_USER=build
CLOUDPC_NAME=b19-02

TEST_MASTER_MACHINE=b19-02

CCD_TEST_ACCOUNT=PROD_win7Test@igware.com
CCD_TEST_ACCOUNT_1=PROD_win7Test_1@igware.com
CCD_TEST_ACCOUNT_2=PROD_win7Test_2@igware.com

USE_ARCHIVED_BUILD=true

# Lab to execute against
LAB=lab16
LAB_DOMAIN_NAME=pc-prod.igware.net
VPLTEST_BRANCH="PROD"
