##########
# This is the buildbot test run configuration file for the 'win32_ul' PRODUCT.
##########

##########
# The following section describes reserved configuration variables.
##########
# DB Info
# To prevent upload of results to the database, comment out at least one of these parameters.
TH_DBNAME=testharness_v2
#TH_DBHOST=mysql.ctbg.acer.com
TH_DBUSER=testharness
TH_DBPWD=route2me

# Name to use in the database for this run
TH_RUN_NAME=woa_3.2_full_against_lab15

# Directory in which to save test run/test case output.
# Results from each suite executed will be saved in a separate directory under this directory
# This can be overridden with the -o testharness command line option.
TH_OUTPUT_DIR=/tmp/testharness/output_woa

# Name of the file where a summary of the test results is written
# This can be overridden with the -s testharness command line option.
#TH_SUMMARY_FILE=/tmp/testharness/output/testharness_summary.out

# Directory in which to look for test suites.
# Default is the sw_x/tests directory in the same tree as the testharness script.
# This can be overridden with the -t testharness command line option.
#TH_TEST_SUITE_DIR=$WORKDIR/sw_x/tests

# The list of suites to run and the order in which to run them.

##########
# Test-run-level environment variables go here.
# They are set in the execution environment of every test case that is executed in this test run.
##########

# Lab to execute against
LAB=lab15
LAB_DOMAIN_NAME=pc.igware.net
INTERNAL_LAB_DOMAIN_NAME=lab15.routefree.com
RUN_FULL_TEST=true
USE_ARCHIVED_BUILD=true

CCD_TEST_ACCOUNT=RC_woaFullTest@igware.com
CCD_TEST_ACCOUNT_1=RC_woaFullTest_1@igware.com
CCD_TEST_ACCOUNT_2=RC_woaFullTest_2@igware.com
