static_cpp_lib(
    name = 'libsimple_http',
    includes = ['include'],
    srcs = [
            'src/http_request.cpp',
            'src/http_response.cpp',
            'src/http_request_async.cpp',
           ],
    deps = [
            '/gvm_core/vplex:libvplex',
           ],
)
