static_cpp_lib(
    name = 'libsync_config_manager',
    includes = ['include'],
    srcs = [
            'src/SyncConfigManager.cpp',
           ],
    deps = [
            '/gvm_core/internal/sync_config:libsync_config',
           ],
)
